### ISSUE TITLE
How to make file public

### ISSUE THREAD

**Issue by lnlwd** [syndbg/webpack-google-cloud-storage-plugin#1]
I need upload and make public the webpack bundle, but i did not see any options in your plugin.

**Comment by syndbg** [comment]
@lnlwd You can do it manually at the moment through Google Cloud Storage by making your bucket public.

**Comment by syndbg** [comment]
However it sounds like something that can be done by `webpack-google-cloud-storage-plugin` out-of-the-box.

**Comment by lnlwd** [comment]
Yep. I think you can create an uploadOption, public (true or false)

**Comment by syndbg** [comment]
Fixed by #3

**Comment by syndbg** [comment]
Also released in npm version `0.7.0`.

**Comment by youanden** [comment]
@syndbg What does the `makePublic` option do? From what I can tell it is what actually makes things public, not `public` - which I have tried unsuccessfully.

https://github.com/syndbg/webpack-google-cloud-storage-plugin/blob/master/src/index.js#L142

**Comment by syndbg** [comment]
@youanden The correct option seems to be `makePublic`. Can you confirm on your end?
